// Custom icon static resources

import {
  AppstoreOutline,
  BarChartOutline,
  ClusterOutline,
  DashboardOutline,
  DatabaseOutline,
  FileTextOutline,
  FolderOutline,
  HomeOutline,
  LaptopOutline,
  LockOutline,
  MessageOutline,
  MinusSquareOutline,
  MonitorOutline,
  PlusSquareOutline,
  RobotOutline,
  SafetyCertificateOutline,
  SafetyOutline,
  SecurityScanOutline,
  SettingOutline,
  TableOutline,
  TeamOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';

export const ICONS = [
  AppstoreOutline,
  BarChartOutline,
  ClusterOutline,
  DashboardOutline,
  DatabaseOutline,
  FileTextOutline,
  FolderOutline,
  HomeOutline,
  LaptopOutline,
  LockOutline,
  MessageOutline,
  MinusSquareOutline,
  MonitorOutline,
  PlusSquareOutline,
  RobotOutline,
  SafetyCertificateOutline,
  SafetyOutline,
  SecurityScanOutline,
  SettingOutline,
  TableOutline,
  TeamOutline,
  UserOutline
];
