// Custom icon static resources

import {
  AppstoreOutline,
  LockOutline,
  UserOutline,
  DashboardOutline,
  SettingOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  SearchOutline,
  BellOutline,
  LogoutOutline,
  RobotOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  ToolOutline,
  LockTwoTone,
  UserAddOutline,
  UserDeleteOutline,
  TeamOutline,
  SafetyOutline,
  ApartmentOutline,
  FundOutline,
  BarChartOutline,
  SafetyCertificateOutline,
  ClusterOutline
} from '@ant-design/icons-angular/icons';

export const ICONS = [
  AppstoreOutline,
  LockOutline,
  UserOutline,
  DashboardOutline,
  SettingOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  SearchOutline,
  BellOutline,
  LogoutOutline,
  RobotOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  ToolOutline,
  LockTwoTone,
  UserAddOutline,
  UserDeleteOutline,
  TeamOutline,
  SafetyOutline,
  ApartmentOutline,
  FundOutline,
  BarChartOutline,
  SafetyCertificateOutline,
  ClusterOutline
];
