/*
 * Automatically generated by 'ng g ng-alain:plugin icon'
 */

import {
  ApiOutline,
  AppstoreOutline,
  ArrowDownOutline,
  ClusterOutline,
  CopyrightOutline,
  CustomerServiceOutline,
  DashboardOutline,
  DatabaseOutline,
  DeploymentUnitOutline,
  ExperimentOutline,
  FileTextOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  HomeOutline,
  LaptopOutline,
  LogoutOutline,
  MessageOutline,
  MonitorOutline,
  RobotOutline,
  SafetyOutline,
  SettingOutline,
  TeamOutline,
  ToolOutline,
  UserOutline,
  BarChartOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  ApiOutline,
  AppstoreOutline,
  ArrowDownOutline,
  ClusterOutline,
  CopyrightOutline,
  CustomerServiceOutline,
  DashboardOutline,
  DatabaseOutline,
  DeploymentUnitOutline,
  ExperimentOutline,
  FileTextOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  HomeOutline,
  LaptopOutline,
  LogoutOutline,
  MessageOutline,
  MonitorOutline,
  RobotOutline,
  SafetyOutline,
  SettingOutline,
  TeamOutline,
  ToolOutline,
  UserOutline,
  BarChartOutline
];
